### ISSUE TITLE
Suspicious warnings in log file

### ISSUE THREAD

**Issue by cplerch** [dokan-dev/dokan-java#11]
# Environment
 * Windows version:  Windows 10 Pro
 * Processor architecture: x64
 * Dokany version:  latest (1.0.4)
 * Library type (Dokany/FUSE): Dokany
 
# Description
I tested mirroring with dokan-java. It generally works fine. Just wanted to report some of the warnings and exceptions I found in the log file:
 * Invalid Structure field in class com.sun.jna.platform.win32.WinBase$WIN32_FIND_DATA, field name 'cFileName' (class [C): Arrays of length zero not allowed: class [C
 * com.dokany.java.DokanyOperationsProxy    : GetFileInformation: /$RECYCLE.BIN/S-1-5-21-514270414-2989288975-3594427135-1002/
   com.dokany.java.DokanyOperationsProxy    : Error reading info: The System cannot find the requested path
 * com.dokany.java.DokanyOperationsProxy    : GetFileInformation: /$Extend/
   com.dokany.java.DokanyOperationsProxy    : Error reading info: The System cannot find the requested path

Are these warnings, particullary the first one listed above, reasons for concern?

# Logs
Pls find attached:
[20170907T093121.zip](https://github.com/dokan-dev/dokan-java/files/1285721/20170907T093121.zip)

**Comment by infeo** [comment]
Since this issue is a year ago and the architecture of the adapter changed, i'll close this issue. If simliar problems appear with the new architecture, just open a new issue.
