### ISSUE TITLE
Repos-Language is marked as C++ instead of Java

### ISSUE THREAD

**Issue by landrix** [dokan-dev/dokan-java#2]
Repos-Language is marked as C++ instead of Java

**Comment by sherter** [comment]
I haven't found a way to tell GitHub explicitly what language should show up for the repository. It displays the language most code is written in (click on the [pink/brown/grey bar](https://github.com/dokan-dev/dokan-java) to see percentages). If it _is_ possible to change this behavior, please tell me how.

**Comment by landrix** [comment]
i found this

https://github.com/github/linguist#overrides

$ cat .gitattributes
dokan-java/src/main/cpp/* linguist-vendored=false

**Comment by sherter** [comment]
I guess you mean `linguist-veondored=true`?!
I don't think this is the right thing to do. Labeling code as `vendored` when it isn't, only to show the *right* language (I'm not even sure if Java _is_ the 'right' language) seems to be wrong. Nevertheless, thanks for the report.
