### ISSUE TITLE
dev.dokan.dokan_java.constants.microsoft.CreateOptions question?

### ISSUE THREAD

**Issue by hrstoyanov** [dokan-dev/dokan-java#29]
Should ```CreateOptions``` implement ```EnumInteger```?  In the "old code" this [was the case](https://github.com/cryptomator/dokany-nio-adapter/blob/develop/src/main/java/com/dokany/java/constants/CreateOptions.java).

**Comment by infeo** [comment]
No. For this you have the [CreateOption](https://github.com/dokan-dev/dokan-java/blob/master/src/main/java/dev/dokan/dokan_java/constants/microsoft/CreateOption.java) class.

For a reasoning see [this comment](https://github.com/dokan-dev/dokan-java/issues/14#issuecomment-437672626).

**Comment by hrstoyanov** [comment]
Ok, so maybe some javadocs to explain which to use when would be very helpful?
