### ISSUE TITLE
Compatible jdokan.dll with 1.x.x

### ISSUE THREAD

**Issue by exaptations** [dokan-dev/dokan-java#3]
Would it be possible for java developers who just want to leverage the java wrapper, and aren't setup to compile jdokan.dll against to have a later snapshot / production release jar with an updated jdokan.dll which is compatible with 0.8.0.x

https://oss.sonatype.org/content/repositories/snapshots/com/github/dokan-dev/dokan-java/dokan-java/0.1-SNAPSHOT/

The jdokan.dll at the above maven GAV isn't compatible with 0.8.0.x

**Comment by sherter** [comment]
I currently don't have the time to keep this wrapper up to date :cry:. If you are interested in helping out, please contact @Maxhy or @Liryna.

**Comment by exaptations** [comment]
Maybe I could what are the steps to build  - note I would need some help on the visual studio tools?

**Comment by sherter** [comment]
Have a look at [appveyor.yml](https://github.com/dokan-dev/dokan-java/blob/master/appveyor.yml). You need to specify `DOKAN_HOME` (and `JAVA_HOME` if not already specified) and then run `gradlew build`.

**Comment by jhult** [comment]
Related to #4 and #10.

You can now use a pre-built version or build yourself using Gradle. See [the README](../blob/master/README.md) for more info.
