### ISSUE TITLE
Problems when simply following the "Building" section in the readme

### ISSUE THREAD

**Issue by markuskreusch** [dokan-dev/dokan-java#4]
I am not a windows / cpp developer so I maybe missing something really basic here and hope you can help me with a quick response.

Tried to build the project as described in the readme. I additionally installed Visual Studio 2013 
because according to the gradle config it is required. 

Afterwards the cpp compilation task can not find windows.h:
`fatal error C1083: Cannot open include file: 'windows.h': No such file or directory`

I tried to set a custom INCLUDE environment variable but that seems to be ignored by gradle:
`:compileNativeSharedLibraryNativeCpp
Ignoring value 'C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Include' set for environment variable 'INCLUDE'.`

Are there any additional configuration steps required to make it work or should it be possible to build right away after installing Visual Studio?

**Comment by sherter** [comment]
I just relaunched the [build on appveyor](https://ci.appveyor.com/project/sherter/jdokan/build/66) and it still seems to build just fine. This is probably related to https://github.com/gradle/gradle/pull/500. Maybe you have multiple versions of Visual Studio installed and gradle picks up the wrong paths?
Please note, however, that this project is currently not maintained by anyone and I can't help you any further.

**Comment by Maxhy** [comment]
@sherter good to know that you definitely stopped to work on it (I was hoping it was temporary). I will try to found another maintainer then. Thanks for your work anyway!

**Comment by markuskreusch** [comment]
I was not aware that this project is no longer maintained but good to know. Thank you for your reply anyway! 

I indeed hat Visual Studio 2015 installed before Visual Studio 2013, maybe this causes the problems. I will report here to maybe help others as soon as I come up with a solution.

**Comment by jhult** [comment]
Building using Visual Studio is no longer required.

You can now use a pre-built version or build yourself using Gradle. See [the README](../blob/master/README.md) for more info.
