### ISSUE TITLE
Unable to bind to DokanRemoveMountPointEx

### ISSUE THREAD

**Issue by infeo** [dokan-dev/dokan-java#40]
Dokany offers three functions in `dokan.h` to unmount a Dokan device:
```cpp
BOOL DOKANAPI DokanUnmount(WCHAR DriveLetter);
BOOL DOKANAPI DokanRemoveMountPoint(LPCWSTR MountPoint);
BOOL DOKANAPI DokanRemoveMountPointEx(LPCWSTR MountPoint, BOOL Safe);
```
The first two functions are also accessible within dokan-java, but if the third is added to the native functions, an `UnsatisfiedLinkException` is thrown because the name cannot be found in the `dokan1.dll`.

This is not suprising, if one inspects the dll with a tool like [Dependencies](https://github.com/lucasg/Dependencies). Also there the `DokanRemoveMountPointEx` is not present.

The question is now why, because the dll is the main entry for the dokany library.

Maybe someone of @dokan-dev/dokan-core can shed some light into this issue.

**Comment by Liryna** [comment]
Hi @infeo ,

Indeed `DokanRemoveMountPointEx` is not exported good job pointing out this. It is only for internal usage. The Safe parameter is not interesting for wrapper or userFS.

It should probably just be moved into `dokani.h` or would you prefer it to be exported ?

**Comment by infeo** [comment]
Mhm, good question.

From the perspective of Java it can be helpful to export it. In general only a few wrapper libs/applications listen to the `DLL_PROCESS_DETACH` signal /recieve it. But they might (and that is possible in Java) offer a way to do a clean up when the application/process terminates. 
dokan-java calls during the clean up `DokanRemoveMountPoint`, which is a delegate to `DokanRemoveMountPointEx(..., TRUE)`. Calling it during termination is accordingly to the documentation maybe not the best idea. Of course, if the function is exported, the documentation needs to be fitted, such that it is clear when to call/use it.

But in the end, this change would make the usage of Dokany more error-prone. Therefore I suggest to move it to `dokani.c` _and_ add internally logic which automatically chooses the correct parameter if the `DokanRemoveMountPoint` is called. (if it is possible)

**Comment by Liryna** [comment]
Thank you for your input @infeo . I moved `DokanRemoveMountPointEx` out of the public header https://github.com/dokan-dev/dokany/commit/a1aaed97400c038f00ce72b41056fce0b8f46211

The library `DLL_PROCESS_DETACH` will always be called and therefore `DokanRemoveMountPointEx` will be called on devices still alive at this stage (that should not happen on a normal termination). I believe `DokanRemoveMountPoint` is safe to call at any moment from the wrapper point of view as a native library should be unloaded after runtime end, no ? And if it is manually loaded, `DokanRemoveMountPoint` can only be called before the manual unload anyways. (I am just arguing if it is needed to adapt the right parameter).

**Comment by infeo** [comment]
Thank you for the fast repsonse!

> from the wrapper point of view as a native library should be unloaded after runtime end

I second that. This also means that we need to make sure, that this is also the way it happens, but this will be another ticket.
