### ISSUE TITLE
Why is onDeleteFile never called?

### ISSUE THREAD

**Issue by CiroOl** [dokan-dev/dokan-java#5]
Running the MemoryFS sample, I noticed onDeleteFile is never called. Is there a particular reason behind that?
I know the project is no longer mantained, but I was hoping someone could help me with this relatively easy question.

**Comment by Liryna** [comment]
Hi @CiroOl ,

What version of Dokan are you using ?

**Comment by CiroOl** [comment]
0.7.2. I coulndt get the latest ones to work

**Comment by Liryna** [comment]
You are testing on Windows 8/10 I guess ?

If so, it is only the version 7.3+ that have the delete fix for windows 8/10
