### ISSUE TITLE
Use JNA?

### ISSUE THREAD

**Issue by soywiz** [dokan-dev/dokan-java#6]
I just found that the dokan project was revived. That's a gread thing.
Lately I have been using Kotlin, a JVM language. And found this.
Are you using JNI instead of JNA for an specific reason? JNA would be much easier to maintain.
I could update this to JNA + Dokan 1.0 if you want.

**Comment by Liryna** [comment]
Oh @soywiz ! This would be awesome and very appreciate ! ❤️ 

If you have any question about the API feel free to ask !

**Comment by jhult** [comment]
Love this.

Pulled from @soywiz's [jna branch](https://github.com/soywiz/dokan-java/tree/jna-100) and it seems to be working well already (using [1.0.1 Windows x64](https://github.com/dokan-dev/dokany/releases/tag/v1.0.1)). 

One thought is can the [DokanFilesystem class](https://github.com/soywiz/dokan-java/blob/jna-100/src/main/java/com/github/dokandev/dokanjava/DokanFilesystem.java) be structured as either:

- an Interface or 
- an Abstract Class with Abstract Methods

? 

I think it would be helpful to know which methods need to be overriden at a bare minimum to make the system function.

I think an Abstract Class (as _DokanFilesystem_ already is), with Abstract Methods for anything required (that should be overriden per Driver) is perhaps the way to go. _DokanFilesystem_ is already partially structured this way. Just adding abstract to those methods which are absolutely needing to be implemented/overriden would be a good step. 

If I can help in any way, please let me know. I'd love to provide some assistance.

**Comment by soywiz** [comment]
Copying a file or creating a folder doesn't seems to work. It keeps trying to create Folder (1), Folder (2), Folder (3)... or File (1), File(2)... not sure why. But probably thought that creating the was not successful.

**Comment by infeo** [comment]
Since the java-wrapper uses now JNA i close the issue
