### ISSUE TITLE
UnsatisfiedLinkError on running the samples

### ISSUE THREAD

**Issue by ihsanhaikalz** [dokan-dev/dokan-java#8]
I am trying to run the samples provided from dokany-java page and when I run it (I already put I:// as run command in Eclipse) it return the error UnstatisfiedLinkError for showVersions() and DokanStatus = DokanStatus.fromInt(Dokan.mount(dokanOptions, this)); command and I am not sure why. I already installed properly Dokany as it is instructed in the github but still no luck. Do you know how to resolve this issue?

Thanks

**Comment by Liryna** [comment]
hi @ihsanhaikalz ,

Dokan java is currently outdated for 1.0.0 and there is a pull request that try to changes the compatibility for it
https://github.com/dokan-dev/dokan-java/pull/7 
I have not tested it myself but you could give a try and help @soywiz on it ?

**Comment by ihsanhaikalz** [comment]
hi @Liryna 

I could try test the pull request but I am not really an expert with Java so maybe I could not help a lot

**Comment by soywiz** [comment]
I will try to finish the PR this weekend if I have some spare time.

Regards

**Comment by infeo** [comment]
I'll guess this issue can also be closed, since its 2 years old.
